version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker-build/api/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:password@pg/blog
      CONFIG: ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - db-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 7s
      timeout: 5s
      retries: 5

volumes:
  db-data: