"""upgrade column pre_post

Revision ID: 05a280033cee
Revises: 9c97308c2ef1
Create Date: 2022-06-19 18:54:22.328856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a280033cee'
down_revision = '9c97308c2ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
