"""upgrade column pre_post 30

Revision ID: 4dc907ff193d
Revises: 05a280033cee
Create Date: 2022-06-19 18:58:55.054204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc907ff193d'
down_revision = '05a280033cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
