"""upgrade column pre_post

Revision ID: 9c97308c2ef1
Revises: ae7d92790ae6
Create Date: 2022-06-19 18:52:39.577933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c97308c2ef1'
down_revision = 'ae7d92790ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
