"""delete column pre_post

Revision ID: af83883952ca
Revises: 4dc907ff193d
Create Date: 2022-06-19 19:02:42.864102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af83883952ca'
down_revision = '4dc907ff193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pre_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pre_post', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
