"""upgrade column pre_post 30

Revision ID: b6c27a369c69
Revises: af83883952ca
Create Date: 2022-06-19 19:03:20.111004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c27a369c69'
down_revision = 'af83883952ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pre_post', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pre_post')
    # ### end Alembic commands ###
