"""update tables

Revision ID: e01651defcdc
Revises: 5e2e2681cd94
Create Date: 2022-06-18 18:30:13.912659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e01651defcdc'
down_revision = '5e2e2681cd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('logged_in', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'logged_in')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
