"""delete logged_out column

Revision ID: fa8bdff27ef2
Revises: e01651defcdc
Create Date: 2022-06-19 17:07:56.015738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8bdff27ef2'
down_revision = 'e01651defcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logged_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logged_out')
    # ### end Alembic commands ###
